# Step 3:
# Source: https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md
# Getting a long-lived Bearer Token for ServiceAccount
# >> kubectl apply -f secret.yaml

# To get the token generated for us behind the scenes:
# >> kubectl get secret admin-user -n kubernetes-dashboard -o jsonpath={".data.token"} | base64 -d

apiVersion: v1
kind: Secret
metadata:
  name: admin-user
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/service-account.name: "admin-user"
type: kubernetes.io/service-account-token
