spring:
  application:
    name: "configserver"
  profiles:
    active: git
  # active: native # not used when using git for config
  cloud:
    config:
      server:
        # native:
        # search-locations: "file:///C://Users//tramb//OneDrive//Documents//microservices//config" # only used for file system config
        # search-locations: "classpath:/config" # not used when using git for config
        git:
          uri: "https://github.com/Shahtr1/microservices-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
encrypt:
  key: "45D81EC1EF61DF8AD8D3E5BB397F9"
management:
  endpoints:
    web:
      exposure:
        include: "*" # enable all management endpoints by the actuator, to support refreshing of configs
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name} # please group all my metrics under my application name, for prometheus
server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
