spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///C://Users//tramb//OneDrive//Documents//microservices//config"
        ## search-locations: "classpath:/config"
server:
  port: 8071
