spring:
  application:
    name: "configserver"
  profiles:
    active: git
  # active: native # not used when using git for config
  cloud:
    config:
      server:
        # native:
        # search-locations: "file:///C://Users//tramb//OneDrive//Documents//microservices//config" # only used for file system config
        # search-locations: "classpath:/config" # not used when using git for config
        git:
          uri: "https://github.com/Shahtr1/microservices-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071
